# Generated by Django 4.1.3 on 2024-03-25 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Номера')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'номера ',
                'verbose_name_plural': 'Региональный номер',
            },
        ),
        migrations.CreateModel(
            name='Category_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Типы')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'типы',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Category_Unaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Наименование отделов')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'подраздиления',
                'verbose_name_plural': 'Подраздиление УНАА',
            },
        ),
        migrations.CreateModel(
            name='Add_Numbers',
            fields=[
                ('number', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Гос номер')),
                ('application', models.CharField(max_length=50, verbose_name='Номер заявки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allgosnumber.category_number', verbose_name='Гос номер')),
                ('category_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allgosnumber.category_types', verbose_name='Типы')),
                ('category_unaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allgosnumber.category_unaa', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Добовления номеров в базу',
                'verbose_name_plural': 'Общая база номеров',
                'ordering': ['-created'],
            },
        ),
    ]
