# Generated by Django 5.0 on 2023-12-12 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=50, unique=True, verbose_name='Регионы')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Добавить регионый номер',
                'verbose_name_plural': 'добавление номера',
            },
        ),
        migrations.CreateModel(
            name='Category_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.CharField(max_length=50, unique=True, verbose_name='Регионы')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Добавить регион',
                'verbose_name_plural': 'добавление региона',
            },
        ),
        migrations.CreateModel(
            name='Category_Unaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=50, unique=True, verbose_name='Отделение')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Добавить подраздиления',
                'verbose_name_plural': 'добавление',
            },
        ),
        migrations.CreateModel(
            name='Add_Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ввод номера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='allgosnumber.category_number')),
                ('category_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='allgosnumber.category_region')),
                ('category_unaa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='allgosnumber.category_unaa')),
            ],
            options={
                'verbose_name': 'Добавить номер',
                'verbose_name_plural': 'Добавление номера',
                'ordering': ['-created'],
            },
        ),
    ]
