# Generated by Django 5.0 on 2023-12-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgosnumber', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_numbers',
            options={'ordering': ['-created'], 'verbose_name': 'Добовления номеров в базу', 'verbose_name_plural': 'Общая база номеров'},
        ),
        migrations.AlterModelOptions(
            name='category_number',
            options={'verbose_name': 'номера ', 'verbose_name_plural': 'Добавить регионый номер'},
        ),
        migrations.AlterModelOptions(
            name='category_region',
            options={'verbose_name': 'регион', 'verbose_name_plural': 'Добавление региона'},
        ),
        migrations.AlterModelOptions(
            name='category_unaa',
            options={'verbose_name': 'подраздиления', 'verbose_name_plural': 'Добавление отдела УНАА'},
        ),
        migrations.AlterField(
            model_name='category_number',
            name='numbers',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номера'),
        ),
    ]
