# Generated by Django 5.0 on 2023-12-13 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgosnumber', '0002_alter_add_numbers_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_number',
            old_name='numbers',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='category_region',
            old_name='regions',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='category_unaa',
            old_name='units',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='add_numbers',
            name='category_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='allgosnumber.category_number', verbose_name='Гос номер'),
        ),
        migrations.AlterField(
            model_name='add_numbers',
            name='category_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='allgosnumber.category_region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='add_numbers',
            name='category_unaa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='allgosnumber.category_unaa', verbose_name='Отделение'),
        ),
    ]
