# Generated by Django 4.1.3 on 2024-03-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgosnumber', '0002_category_types_alter_add_numbers_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_numbers',
            name='id',
        ),
        migrations.AlterField(
            model_name='add_numbers',
            name='number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Гос номер'),
        ),
    ]
