# Generated by Django 5.0 on 2023-12-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgosnumber', '0003_rename_numbers_category_number_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_numbers',
            options={'ordering': ['created'], 'verbose_name': 'Добовления номеров в базу', 'verbose_name_plural': 'Общая база номеров'},
        ),
        migrations.AlterField(
            model_name='category_number',
            name='title',
            field=models.IntegerField(max_length=2, unique=True, verbose_name='Номера'),
        ),
    ]
