# Generated by Django 5.0 on 2023-12-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgosnumber', '0004_alter_add_numbers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_number',
            name='title',
            field=models.CharField(max_length=2, unique=True, verbose_name='Номера'),
        ),
    ]
