# Generated by Django 5.0 on 2023-12-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgosnumber', '0006_alter_category_number_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_number',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номера'),
        ),
    ]
