# Generated by Django 4.1.3 on 2023-12-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allgosnumber', '0008_category_types_alter_category_number_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_numbers',
            options={'ordering': ['-created'], 'verbose_name': 'Добовления номеров в базу', 'verbose_name_plural': 'Общая база номеров'},
        ),
    ]
