version: "3.8"

services:
  app:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: run
    volumes:
      - ./media:/app/media
      - ./static:/app/backend/static
    env_file: .env
    ports:
      - 0.0.0.0:8000:8000
volumes:
  unaa-data: